#!/usr/bin/env python3
"""Download, verify, and configure one Orislop complete-stack HF release."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
from typing import Any, Sequence


REVISION_RE = re.compile(r"^[0-9a-fA-F]{40}$")


class MaterializeError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_manifest(root: Path) -> dict[str, Any]:
    path = root / "artifact_manifest.json"
    if not path.is_file():
        raise MaterializeError(f"Complete-stack manifest is missing: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("artifactType") != "orislop-complete-runnable-stack":
        raise MaterializeError("HF repository is not an Orislop complete-stack release")
    if not isinstance(payload.get("files"), dict) or not payload["files"]:
        raise MaterializeError("Complete-stack manifest has no file inventory")
    return payload


def verify(root: Path, manifest: dict[str, Any]) -> None:
    expected_root = root.resolve()
    for index, (relative, record) in enumerate(manifest["files"].items(), start=1):
        target = (root / relative).resolve()
        if not target.is_relative_to(expected_root):
            raise MaterializeError(f"Unsafe manifest path: {relative}")
        if not target.is_file():
            raise MaterializeError(f"Complete-stack file is missing: {relative}")
        if target.stat().st_size != int(record["bytes"]):
            raise MaterializeError(f"Complete-stack size mismatch: {relative}")
        actual = sha256_file(target)
        if actual != str(record["sha256"]).lower():
            raise MaterializeError(f"Complete-stack SHA-256 mismatch: {relative}")
        if index % 25 == 0:
            print(f"[verify] {index}/{len(manifest['files'])}", flush=True)


def manifest_sha(manifest: dict[str, Any], relative: str) -> str:
    record = manifest["files"].get(relative)
    if not isinstance(record, dict):
        raise MaterializeError(f"Manifest does not contain required file: {relative}")
    digest = str(record.get("sha256") or "").lower()
    if re.fullmatch(r"[0-9a-f]{64}", digest) is None:
        raise MaterializeError(f"Manifest has an invalid hash for: {relative}")
    return digest


def require_path(root: Path, relative: str, *, directory: bool = False) -> Path:
    target = (root / relative).resolve()
    expected = target.is_dir() if directory else target.is_file()
    if not expected:
        kind = "directory" if directory else "file"
        raise MaterializeError(f"Required complete-stack {kind} is missing: {relative}")
    return target


def env_lines(root: Path, manifest: dict[str, Any], repo: str, revision: str) -> list[str]:
    temporal = require_path(root, "orislop/temporal/final_model_package", directory=True)
    temporal_weights_relative = next(
        name
        for name in (
            "orislop/temporal/final_model_package/final_model.safetensors",
            "orislop/temporal/final_model_package/final_model.pt",
        )
        if (root / name).is_file()
    )
    av_model = require_path(root, "orislop/av/orislop_av_joint_v1.ts")
    av_metadata = require_path(root, "orislop/av/orislop_av_joint_v1.json")
    yunet = require_path(root, "orislop/av/face_detection_yunet_2023mar.onnx")
    fusion = require_path(root, "orislop/temporal/phase2_av/stage2_temporal_av_fusion.pt")
    calibration = require_path(root, "orislop/temporal/phase2_av/stage3_temporal_av_calibration.pt")
    standalone_spatial = require_path(root, "orislop/spatial/standalone/fusion_model_cls_v2.pt")
    ai_model = require_path(root, "upstream/lightweight-ai-image-detector", directory=True)
    vision_model = require_path(root, "upstream/vit-base-patch16-224", directory=True)
    public_frame = require_path(root, "upstream/public-frame-detector", directory=True)
    aegis = require_path(root, "upstream/aegis-motion/checkpoint_best.pt")
    whisper = require_path(root, "upstream/faster-whisper-tiny", directory=True)
    qwen = require_path(
        root,
        "upstream/qwen2.5-1.5b-instruct-gguf/qwen2.5-1.5b-instruct-q4_k_m.gguf",
    )
    return [
        "# Generated by materialize_complete_stack.py; contains no secrets.",
        f"ORISLOP_COMPLETE_STACK_REPO={repo}",
        f"ORISLOP_COMPLETE_STACK_REVISION={revision}",
        f"ORISLOP_COMPLETE_STACK_ROOT={root}",
        "ORISLOP_REQUIRE_FULL_MODEL_STACK=1",
        "ORISLOP_TEMPORAL_ENABLED=1",
        f"ORISLOP_TEMPORAL_PACKAGE_PATH={temporal}",
        "ORISLOP_TEMPORAL_HF_REPO_ID=",
        "ORISLOP_TEMPORAL_HF_REVISION=",
        f"ORISLOP_TEMPORAL_MODEL_SHA256={manifest_sha(manifest, temporal_weights_relative)}",
        "ORISLOP_TEMPORAL_LEGACY_FALLBACK=0",
        "ORISLOP_TEMPORAL_ROLLOUT=corroborated",
        "ORISLOP_AV_JOINT_ENABLED=1",
        f"ORISLOP_AV_JOINT_MODEL_PATH={av_model}",
        f"ORISLOP_AV_JOINT_METADATA_PATH={av_metadata}",
        f"ORISLOP_YUNET_MODEL_PATH={yunet}",
        f"ORISLOP_YUNET_MODEL_SHA256={manifest_sha(manifest, 'orislop/av/face_detection_yunet_2023mar.onnx')}",
        f"ORISLOP_TEMPORAL_AV_FUSION_PATH={fusion}",
        f"ORISLOP_TEMPORAL_AV_CALIBRATION_PATH={calibration}",
        f"ORISLOP_SPATIAL_CHECKPOINT_PATH={standalone_spatial}",
        f"ORISLOP_AI_MODEL_SOURCE={ai_model}",
        f"ORISLOP_VISION_MODEL_SOURCE={vision_model}",
        f"ORISLOP_PUBLIC_FRAME_MODEL_DIR={public_frame}",
        f"ORISLOP_AEGIS_CHECKPOINT_PATH={aegis}",
        f"ORISLOP_TRANSCRIPTION_MODEL={whisper}",
        f"ORISLOP_OLLAMA_GGUF_PATH={qwen}",
        f"ORISLOP_OLLAMA_GGUF_SHA256={manifest_sha(manifest, 'upstream/qwen2.5-1.5b-instruct-gguf/qwen2.5-1.5b-instruct-q4_k_m.gguf')}",
        "ORISLOP_OLLAMA_MODEL=orislop-qwen2.5:1.5b-instruct",
        "ORISLOP_CLIP_MODEL_SOURCE=openai/clip-vit-base-patch32",
        "ORISLOP_TEMPORAL_CLIP_MODEL_SOURCE=openai/clip-vit-base-patch32",
        "ORISLOP_TEMPORAL_CLIP_MODEL_REVISION=3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268",
        "ORISLOP_SPATIAL_DEVICE=cuda",
        "ORISLOP_SPATIAL_AUX_DEVICE=cpu",
        "ORISLOP_TRANSCRIPTION_DEVICE=cpu",
        "ORISLOP_TRANSCRIPTION_COMPUTE_TYPE=int8",
        "ORISLOP_CLOUD_BETA_AUTOMATIC_HIDES=0",
        "ORISLOP_VISUAL_ROLLOUT_MODE=shadow",
    ]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default="gonnerthetooner/orislop-complete-stack-v1")
    parser.add_argument("--revision", required=True, help="Full 40-character HF commit")
    parser.add_argument("--destination", default="/models/orislop-complete-stack")
    parser.add_argument("--env-output", default="/models/orislop-complete-stack/model.env")
    parser.add_argument("--token", default=None)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if REVISION_RE.fullmatch(args.revision) is None:
        raise MaterializeError("--revision must be a full immutable 40-character commit")
    try:
        from huggingface_hub import snapshot_download
    except ImportError as error:
        raise MaterializeError("Install huggingface-hub before materializing the release") from error
    destination = Path(args.destination).expanduser().resolve()
    destination.mkdir(parents=True, exist_ok=True)
    snapshot = Path(snapshot_download(
        repo_id=args.repo,
        revision=args.revision,
        token=args.token or os.environ.get("HF_TOKEN") or None,
        local_dir=str(destination),
    )).resolve()
    manifest = load_manifest(snapshot)
    verify(snapshot, manifest)
    env_output = Path(args.env_output).expanduser().resolve()
    env_output.parent.mkdir(parents=True, exist_ok=True)
    temporary = env_output.with_suffix(env_output.suffix + ".tmp")
    temporary.write_text("\n".join(env_lines(snapshot, manifest, args.repo, args.revision)) + "\n", encoding="utf-8")
    os.replace(temporary, env_output)
    print(json.dumps({
        "status": "complete-stack-materialized",
        "repo": args.repo,
        "revision": args.revision,
        "root": str(snapshot),
        "env": str(env_output),
        "source": str(snapshot / "runtime" / "source"),
        "verifiedFiles": len(manifest["files"]),
        "completeOffline": bool(manifest.get("completeOffline")),
    }, indent=2), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
