#!/usr/bin/env bash
set -Eeuo pipefail

# Internal detached worker. Start it through orislop_vast_manager.py so PID,
# duplicate-launch, readiness, and logs stay coherent.

ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
ROOT="$(cd "$ROOT" && pwd)"
MANAGER="$ROOT/scripts/orislop_vast_manager.py"
BOOTSTRAP="$ROOT/scripts/vast3090-bootstrap.sh"
MATERIALIZER="$ROOT/scripts/materialize_complete_stack.py"
SUPERVISOR="$ROOT/apps/detector-bridge/vast_supervisor.py"
VENV="${ORISLOP_VENV:-/opt/orislop-venv}"
MODEL_ROOT="${ORISLOP_COMPLETE_STACK_ROOT:-/models/orislop-complete-stack}"
MODEL_ENV="$MODEL_ROOT/model.env"
STATUS_FILE="${ORISLOP_STATUS_ROOT:-/run/orislop-vast}/status.json"

phase() {
  python3 "$MANAGER" --root "$ROOT" _write-phase "$1" --detail "${2:-}"
}

on_error() {
  local status=$?
  phase failed "Startup stopped in phase ${ORISLOP_ACTIVE_PHASE:-unknown}; see the detailed log."
  exit "$status"
}
trap on_error ERR

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "[orislop-vast] Hugging Face access is not configured. Export a newly rotated HF_TOKEN; this launcher never prompts." >&2
  exit 2
fi
for required in "$MANAGER" "$BOOTSTRAP" "$MATERIALIZER" "$SUPERVISOR"; do
  if [[ ! -f "$required" ]]; then
    echo "[orislop-vast] This package is incomplete; missing $required" >&2
    exit 2
  fi
done

ORISLOP_ACTIVE_PHASE=dependencies
export ORISLOP_ACTIVE_PHASE
phase dependencies "Installing only missing OS and pinned Python dependencies."
ORISLOP_BOOTSTRAP_INSTALL_ONLY=1 bash "$BOOTSTRAP" "$ROOT"

ORISLOP_ACTIVE_PHASE=environment-validation
export ORISLOP_ACTIVE_PHASE
phase environment-validation "Checking CUDA, VRAM, CPU, RAM, and manifest-aware storage."
ORISLOP_TEMPORAL_ENABLED=0 \
ORISLOP_REQUIRE_FULL_MODEL_STACK=0 \
"$VENV/bin/python" -u "$SUPERVISOR" --preflight-only

ORISLOP_ACTIVE_PHASE=download
export ORISLOP_ACTIVE_PHASE
phase download "Reusing verified files and retrying only missing or corrupt release files."
"$VENV/bin/python" -u "$MATERIALIZER" \
  --repo "$ORISLOP_COMPLETE_STACK_REPO" \
  --revision "$ORISLOP_COMPLETE_STACK_REVISION" \
  --destination "$MODEL_ROOT" \
  --env-output "$MODEL_ENV" \
  --expected-manifest-sha256 "$ORISLOP_EXPECTED_MANIFEST_SHA256" \
  --expected-release-bytes "$ORISLOP_EXPECTED_RELEASE_BYTES" \
  --status-file "$STATUS_FILE"

set -a
# Generated by the verified materializer and explicitly contains no secrets.
# shellcheck disable=SC1090
source "$MODEL_ENV"
set +a

# The Hugging Face token is needed only by the read-only materializer. The
# detector receives verified local paths and does not inherit the token.
unset HF_TOKEN
export ORISLOP_APP_ROOT="$ROOT"
export ORISLOP_MODEL_ROOT="${ORISLOP_MODEL_ROOT:-/models}"
export ORISLOP_STATUS_ROOT="${ORISLOP_STATUS_ROOT:-/run/orislop-vast}"
export ORISLOP_ALLOWED_EXTENSION_ORIGINS="${ORISLOP_ALLOWED_EXTENSION_ORIGINS}"
export ORISLOP_DETECTOR_PORT="${ORISLOP_DETECTOR_PORT:-4317}"
export ORISLOP_CLOUD_HEAVY_ENABLED=1
export ORISLOP_PRELOAD_HEAVY_MODE=1
export ORISLOP_STARTUP_TIMEOUT_SECONDS="${ORISLOP_STARTUP_TIMEOUT_SECONDS:-3600}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:256}"

ORISLOP_ACTIVE_PHASE=benchmark
export ORISLOP_ACTIVE_PHASE
phase benchmark "Startup safety checks complete; data-dependent autotune remains deferred to the first Heavy request."
echo "[benchmark] No fake media benchmark was run. First-run autotune will log its own benchmark state on the first Heavy request."

ORISLOP_ACTIVE_PHASE=model-loading
export ORISLOP_ACTIVE_PHASE
phase model-loading "Starting Ollama and loading every required detector model."
exec "$VENV/bin/python" -u "$SUPERVISOR"
