#!/usr/bin/env bash
set -Eeuo pipefail

# One-command Vast path for the coherent HF release. The private environment
# file contains only operator secrets; the generated model.env contains only
# verified local artifact paths and may be regenerated safely.

ROOT="${1:-$(pwd)}"
ROOT="$(cd "$ROOT" && pwd)"
BASE_BOOTSTRAP="$ROOT/scripts/vast3090-bootstrap.sh"
MATERIALIZER="$ROOT/scripts/materialize_complete_stack.py"
VENV="${ORISLOP_VENV:-/opt/orislop-venv}"
REPO="${ORISLOP_COMPLETE_STACK_REPO:-gonnerthetooner/orislop-complete-stack-v1}"
REVISION="${ORISLOP_COMPLETE_STACK_REVISION:-}"
DESTINATION="${ORISLOP_COMPLETE_STACK_ROOT:-/models/orislop-complete-stack}"
MODEL_ENV="$DESTINATION/model.env"
PRIVATE_ENV="${ORISLOP_ENV_FILE:-}"

if [[ ! -f "$BASE_BOOTSTRAP" || ! -f "$MATERIALIZER" ]]; then
  echo "[complete-bootstrap] Run from the extracted Orislop complete-stack source." >&2
  exit 1
fi
if [[ ! "$REVISION" =~ ^[0-9a-fA-F]{40}$ ]]; then
  echo "[complete-bootstrap] ORISLOP_COMPLETE_STACK_REVISION must be the full HF commit." >&2
  exit 1
fi

echo "[complete-bootstrap] installing runtime dependencies"
ORISLOP_BOOTSTRAP_INSTALL_ONLY=1 bash "$BASE_BOOTSTRAP" "$ROOT"

if [[ -n "$PRIVATE_ENV" ]]; then
  # The base bootstrap already validated that this is a private 0400/0600 file.
  set -a
  # shellcheck disable=SC1090
  source "$PRIVATE_ENV"
  set +a
fi

echo "[complete-bootstrap] downloading and hashing complete model repository"
"$VENV/bin/python" "$MATERIALIZER" \
  --repo "$REPO" \
  --revision "$REVISION" \
  --destination "$DESTINATION" \
  --env-output "$MODEL_ENV"

set -a
# shellcheck disable=SC1090 -- generated by the verified materializer above.
source "$MODEL_ENV"
set +a

# Keep already-exported secrets, but prevent the older private file from
# overriding the generated verified model paths during the second bootstrap.
unset ORISLOP_ENV_FILE
echo "[complete-bootstrap] starting Orislop from verified local artifacts"
exec bash "$BASE_BOOTSTRAP" "$ROOT"
